---
title: "黄金技术指标跟踪"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. 说明

本文基于私募排排网公布的数据进行整理出图。
 

1）在2018年3月，参考板块指数市场强度：创业板> 港股通 > 上证 。
 
2）在2018年3月，赤子之心价值基金推荐板块指数市场强度：医药 > 高端装备 > 消费。
 
3）截止到2018年3月底，赤子之心价值基金收益率为1%，跑赢了沪深300，中证500和深证红利。
 
4）截止到2018年3月底，作为趋势型代表的展博1期收益率为-8%。
 作为价值型代表的景林稳健基金收益率为-4%。

## 2. 月预测

### 2.1 黄金的KDJ月线走势预测

说明：最右端的淡蓝色线与红色线分别为KDJ.D与KDJ.K的向前5月预测

```{r , fig.height=10, fig.width=14, echo=FALSE}
source("D:\\MyR\\stock\\PrepareDataAndDrawMonthlyKDJDPlot.R")
```

### 2.2 黄金的本月价格波动区间预测

说明：依据Arima模型对黄金的月复合收益率建模，然后对金价进行预测

```{r , fig.height=3, fig.width=4, echo=FALSE}
source("D:\\MyR\\stock\\PrepareDataAndComputePriceRangeForNextMonth.R")
```

### 2.3 黄金月收益率的历史波动情况回溯

```{r , fig.height=2, fig.width=9, echo=FALSE}
source("D:\\MyR\\stock\\PrepareDataAndShowRecentMonthSituation.R")
```

## 3. 周预测

### 3.1 黄金的KDJ周线走势预测

说明：最右端的淡蓝色线与红色线分别为KDJ.D与KDJ.K的向前5周预测

```{r , fig.height=10, fig.width=14, echo=FALSE}
source("D:\\MyR\\stock\\PrepareDataAndDrawWeeklyKDJDPlot.R")
```
